FROM oven/bun:1.2.5 AS BUILDER

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

# These two are passed as non container ENV intentionally.
RUN NODE_OPTIONS='--max-old-space-size=8192' \
    NEXT_CPU_COUNT=$(nproc) \
    bun --bun next build

FROM oven/bun:1.2.5-alpine

WORKDIR /app

ENV HOSTNAME=0.0.0.0

COPY --from=BUILDER /app/.next/standalone ./
COPY --from=BUILDER /app/.next/static ./.next/static
COPY --from=BUILDER /app/public ./public

EXPOSE 3000

CMD ["bun", "server.js"]